name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install Android components
        run: sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build release APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
          gradle-version: 8.7
