name: Android CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build release APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'
          arguments: assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: immersive-index-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: warn
